### ISSUE TITLE
openssl license

### ISSUE THREAD

**Issue by W-M-D** [pwarren/rtl-entropy#19]
rtl-entropy uses openssl libs to build however it only has a gpl license. The fix is detailed here https://lists.debian.org/debian-legal/2004/05/msg00595.html

**Comment by pwarren** [comment]
Hrm, that's a bit silly :(  I think for now I'll add the exception, with the idea to migrate to GnuTLS in the experimental branch.

**Comment by pwarren** [comment]
Fixed in commit: 05a778430f4260e3e9256e6edc3ab4ae7a61b4d2
