### ISSUE TITLE
USB Error while reading with rtl_entropy

### ISSUE THREAD

**Issue by webernetz** [pwarren/rtl-entropy#22]
Hi. I am currently testing with rtl_entropy and after a few hours of reading from the fifo file, the daemon process stopped. I can see the following messges from "demsg":
[132219.399908] usb 1-1.2: usbfs: usb_submit_urb returned -121
[295885.710820] usb 1-1.2: usbfs: usb_submit_urb returned -121

Is this related to rtl_entropy, or to some other errors?
Thanks.

**Comment by pwarren** [comment]
That's not something I've seen and from a quick search, seems to be an interaction with slightly dodgy hardware and the USB stack.  Does your motherboard have a separate USB controller that you could try it with?

**Comment by webernetz** [comment]
Hi Paul,
thanks for your comment. I am using a Raspberry Pi for it. I will try it with another within the next days.
Thanks!
Johannes

**Comment by webernetz** [comment]
Hey Paul,
I am currently using the stick on another Raspberry Pi without any problems. So you are probably right that it was a kind of hardware problem on the other (older) Pi.
Thanks!
