### ISSUE TITLE
What's the samplerate for?

### ISSUE THREAD

**Issue by webernetz** [pwarren/rtl-entropy#24]
Hello Paul,

I have a question concerning the samplerate (-s <value>). What exactly does it? When I am running your program with the default value nothing passes the FIPS tests. But when I decrease the value to "-s 2.4M" I get much random data.
I am confused because to my mind the samplerate is the speed of reading out the data from the stick which should not change the entropy, isn't it?

Thanks a lot!
Johannes

**Comment by pwarren** [comment]
So the -s parameter of rtl_entropy exposes the samplerate parameter of the underlying rtl-sdr library.  It correlates with the bandwidth of the sampled RF. So a 2MHz sample rate gives you data from your centre frequency -1 and +1 MHz.  Lower sample rates use less CPU to turn that RF stream in to useful entropy. Pretty much any x86 computer that can still run Chrome shoudl be easily able to cope with the full 3MHz bandwidth, raspberry pi and other similar devices might struggle at that rate.

**Comment by kovacs-andras** [comment]
Better late than never. :D Thanks!

**Comment by Remmy** [comment]
Unless I am misunderstanding, I don't yet see how this explains the failing FIPS tests?
