### ISSUE TITLE
Does your code work with a USB RTL-SDR device on a router ?

### ISSUE THREAD

**Issue by uihdff** [pwarren/rtl-entropy#25]
@pwarren,

Does your code work with a USB RTL-SDR device on a Linux based router like the one below ?

RTL-SDR Blog R820T2 RTL2832U 1PPM TCXO SMA Software Defined Radio with 2x Telescopic Antennas 

[https://www.amazon.com/RTL-SDR-Blog-RTL2832U-Software-Telescopic/dp/B011HVUEME/ref=sr_1_1?ie=UTF8&qid=1494267564&sr=8-1&keywords=B011HVUEME](url)

**Comment by pwarren** [comment]
The you linked to is the SDR dongle, my code will work fine with that. I've not compiled it for any embedded platforms other than a raspberry pi, but it should work fine on any platform with the required libraries.

Cheers
