### ISSUE TITLE
Cannot build 

### ISSUE THREAD

**Issue by ieei4n7u1710n** [pwarren/rtl-entropy#26]
flowforger@anv1l0:~$ git clone https://github.com/pwarren/rtl-entropy/
Cloning into 'rtl-entropy'...
remote: Counting objects: 794, done.
remote: Total 794 (delta 0), reused 0 (delta 0), pack-reused 794
Receiving objects: 100% (794/794), 197.91 KiB | 0 bytes/s, done.
Resolving deltas: 100% (487/487), done.
flowforger@anv1l0:~$ cd rtl-entropy/
flowforger@anv1l0:~/rtl-entropy$ ls
cmake           CryptoNotes.txt  LICENSE          README.md          src
CMakeLists.txt  debian           LICENSE.openssl  rtl-entropy.pc.in
flowforger@anv1l0:~/rtl-entropy$ mkdir build
flowforger@anv1l0:~/rtl-entropy$ cd build
flowforger@anv1l0:~/rtl-entropy/build$ cmake ../
-- The C compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Build type not specified: defaulting to release.
-- Extracting version information from git describe...
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29") 
-- Checking for module 'librtlsdr'
--   No package 'librtlsdr' found
-- librtlsdr not found.
-- Checking for module 'libbladeRF'
--   No package 'libbladeRF' found
-- libbladeRF not found.
-- Checking for module 'openssl'
--   No package 'openssl' found
-- Could NOT find OpenSSL (missing:  OPENSSL_LIBRARIES OPENSSL_INCLUDE_DIRS) 
-- Found LibCAP 
CMake Warning (dev) at CMakeLists.txt:120 (link_directories):
  This command specifies the relative path

    LIBRTLSDR_LIBRARIES-NOTFOUND

  as a link directory.

  Policy CMP0015 is not set: link_directories() treats paths relative to the
  source dir.  Run "cmake --help-policy CMP0015" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Building for version: 0.1.2 / 0.1.2
-- Using install prefix: /usr/local
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBRTLSDR_INCLUDE_DIRS (ADVANCED)
   used as include directory in directory /home/flowforger/rtl-entropy
   used as include directory in directory /home/flowforger/rtl-entropy
   used as include directory in directory /home/flowforger/rtl-entropy
   used as include directory in directory /home/flowforger/rtl-entropy
   used as include directory in directory /home/flowforger/rtl-entropy
   used as include directory in directory /home/flowforger/rtl-entropy
   used as include directory in directory /home/flowforger/rtl-entropy
   used as include directory in directory /home/flowforger/rtl-entropy/src
   used as include directory in directory /home/flowforger/rtl-entropy/src
   used as include directory in directory /home/flowforger/rtl-entropy/src
   used as include directory in directory /home/flowforger/rtl-entropy/src
   used as include directory in directory /home/flowforger/rtl-entropy/src
   used as include directory in directory /home/flowforger/rtl-entropy/src
   used as include directory in directory /home/flowforger/rtl-entropy/src
OPENSSL_INCLUDE_DIR
   used as include directory in directory /home/flowforger/rtl-entropy
   used as include directory in directory /home/flowforger/rtl-entropy
   used as include directory in directory /home/flowforger/rtl-entropy
   used as include directory in directory /home/flowforger/rtl-entropy
   used as include directory in directory /home/flowforger/rtl-entropy
   used as include directory in directory /home/flowforger/rtl-entropy
   used as include directory in directory /home/flowforger/rtl-entropy
   used as include directory in directory /home/flowforger/rtl-entropy/src
   used as include directory in directory /home/flowforger/rtl-entropy/src
   used as include directory in directory /home/flowforger/rtl-entropy/src
   used as include directory in directory /home/flowforger/rtl-entropy/src
   used as include directory in directory /home/flowforger/rtl-entropy/src
   used as include directory in directory /home/flowforger/rtl-entropy/src
   used as include directory in directory /home/flowforger/rtl-entropy/src

-- Configuring incomplete, errors occurred!
See also "/home/flowforger/rtl-entropy/build/CMakeFiles/CMakeOutput.log".
flowforger@anv1l0:~/rtl-entropy/build$ cat /home/flowforger/rtl-e^C
flowforger@anv1l0:~/rtl-entropy/build$ cat CMakeFiles/CMakeOutput.log 
The system is: Linux - 4.9.0-3-amd64 - x86_64
Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
Compiler: /usr/bin/cc 
Build flags: 
Id flags: 

The output was:
0

Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"

The C compiler identification is GNU, found in "/home/flowforger/rtl-entropy/build/CMakeFiles/3.7.2/CompilerIdC/a.out"

Determining if the C compiler works passed with the following output:
Change Dir: /home/flowforger/rtl-entropy/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_aea52/fast"
/usr/bin/make -f CMakeFiles/cmTC_aea52.dir/build.make CMakeFiles/cmTC_aea52.dir/build
make[1]: Entering directory '/home/flowforger/rtl-entropy/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_aea52.dir/testCCompiler.c.o
/usr/bin/cc     -o CMakeFiles/cmTC_aea52.dir/testCCompiler.c.o   -c /home/flowforger/rtl-entropy/build/CMakeFiles/CMakeTmp/testCCompiler.c
Linking C executable cmTC_aea52
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_aea52.dir/link.txt --verbose=1
/usr/bin/cc       CMakeFiles/cmTC_aea52.dir/testCCompiler.c.o  -o cmTC_aea52 -rdynamic 
make[1]: Leaving directory '/home/flowforger/rtl-entropy/build/CMakeFiles/CMakeTmp'

Detecting C compiler ABI info compiled with the following output:
Change Dir: /home/flowforger/rtl-entropy/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_98fbb/fast"
/usr/bin/make -f CMakeFiles/cmTC_98fbb.dir/build.make CMakeFiles/cmTC_98fbb.dir/build
make[1]: Entering directory '/home/flowforger/rtl-entropy/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_98fbb.dir/CMakeCCompilerABI.c.o
/usr/bin/cc     -o CMakeFiles/cmTC_98fbb.dir/CMakeCCompilerABI.c.o   -c /usr/share/cmake-3.7/Modules/CMakeCCompilerABI.c
Linking C executable cmTC_98fbb
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_98fbb.dir/link.txt --verbose=1
/usr/bin/cc      -v CMakeFiles/cmTC_98fbb.dir/CMakeCCompilerABI.c.o  -o cmTC_98fbb -rdynamic  
Using built-in specs.
COLLECT_GCC=/usr/bin/cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 6.3.0-18' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 6.3.0 20170516 (Debian 6.3.0-18) 
COMPILER_PATH=/usr/lib/gcc/x86_64-linux-gnu/6/:/usr/lib/gcc/x86_64-linux-gnu/6/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/6/:/usr/lib/gcc/x86_64-linux-gnu/
LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/6/:/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/6/../../../../lib/:/lib/x86_64-linux-gnu/:/lib/../lib/:/usr/lib/x86_64-linux-gnu/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-linux-gnu/6/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-v' '-o' 'cmTC_98fbb' '-rdynamic' '-mtune=generic' '-march=x86-64'
 /usr/lib/gcc/x86_64-linux-gnu/6/collect2 -plugin /usr/lib/gcc/x86_64-linux-gnu/6/liblto_plugin.so -plugin-opt=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper -plugin-opt=-fresolution=/tmp/cc24JM9b.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --sysroot=/ --build-id --eh-frame-hdr -m elf_x86_64 --hash-style=gnu -export-dynamic -dynamic-linker /lib64/ld-linux-x86-64.so.2 -pie -o cmTC_98fbb /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/Scrt1.o /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/6/crtbeginS.o -L/usr/lib/gcc/x86_64-linux-gnu/6 -L/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/6/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/6/../../.. CMakeFiles/cmTC_98fbb.dir/CMakeCCompilerABI.c.o -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/lib/gcc/x86_64-linux-gnu/6/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/crtn.o
COLLECT_GCC_OPTIONS='-v' '-o' 'cmTC_98fbb' '-rdynamic' '-mtune=generic' '-march=x86-64'
make[1]: Leaving directory '/home/flowforger/rtl-entropy/build/CMakeFiles/CMakeTmp'

Parsed C implicit link information from above output:
  link line regex: [^( *|.*[/\])(ld|([^/\]+-)?ld|collect2)[^/\]*( |$)]
  ignore line: [Change Dir: /home/flowforger/rtl-entropy/build/CMakeFiles/CMakeTmp]
  ignore line: []
  ignore line: [Run Build Command:"/usr/bin/make" "cmTC_98fbb/fast"]
  ignore line: [/usr/bin/make -f CMakeFiles/cmTC_98fbb.dir/build.make CMakeFiles/cmTC_98fbb.dir/build]
  ignore line: [make[1]: Entering directory '/home/flowforger/rtl-entropy/build/CMakeFiles/CMakeTmp']
  ignore line: [Building C object CMakeFiles/cmTC_98fbb.dir/CMakeCCompilerABI.c.o]
  ignore line: [/usr/bin/cc     -o CMakeFiles/cmTC_98fbb.dir/CMakeCCompilerABI.c.o   -c /usr/share/cmake-3.7/Modules/CMakeCCompilerABI.c]
  ignore line: [Linking C executable cmTC_98fbb]
  ignore line: [/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_98fbb.dir/link.txt --verbose=1]
  ignore line: [/usr/bin/cc      -v CMakeFiles/cmTC_98fbb.dir/CMakeCCompilerABI.c.o  -o cmTC_98fbb -rdynamic  ]
  ignore line: [Using built-in specs.]
  ignore line: [COLLECT_GCC=/usr/bin/cc]
  ignore line: [COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper]
  ignore line: [Target: x86_64-linux-gnu]
  ignore line: [Configured with: ../src/configure -v --with-pkgversion='Debian 6.3.0-18' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu]
  ignore line: [Thread model: posix]
  ignore line: [gcc version 6.3.0 20170516 (Debian 6.3.0-18) ]
  ignore line: [COMPILER_PATH=/usr/lib/gcc/x86_64-linux-gnu/6/:/usr/lib/gcc/x86_64-linux-gnu/6/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/6/:/usr/lib/gcc/x86_64-linux-gnu/]
  ignore line: [LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/6/:/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/6/../../../../lib/:/lib/x86_64-linux-gnu/:/lib/../lib/:/usr/lib/x86_64-linux-gnu/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-linux-gnu/6/../../../:/lib/:/usr/lib/]
  ignore line: [COLLECT_GCC_OPTIONS='-v' '-o' 'cmTC_98fbb' '-rdynamic' '-mtune=generic' '-march=x86-64']
  link line: [ /usr/lib/gcc/x86_64-linux-gnu/6/collect2 -plugin /usr/lib/gcc/x86_64-linux-gnu/6/liblto_plugin.so -plugin-opt=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper -plugin-opt=-fresolution=/tmp/cc24JM9b.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --sysroot=/ --build-id --eh-frame-hdr -m elf_x86_64 --hash-style=gnu -export-dynamic -dynamic-linker /lib64/ld-linux-x86-64.so.2 -pie -o cmTC_98fbb /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/Scrt1.o /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/6/crtbeginS.o -L/usr/lib/gcc/x86_64-linux-gnu/6 -L/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/6/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/6/../../.. CMakeFiles/cmTC_98fbb.dir/CMakeCCompilerABI.c.o -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/lib/gcc/x86_64-linux-gnu/6/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/crtn.o]
    arg [/usr/lib/gcc/x86_64-linux-gnu/6/collect2] ==> ignore
    arg [-plugin] ==> ignore
    arg [/usr/lib/gcc/x86_64-linux-gnu/6/liblto_plugin.so] ==> ignore
    arg [-plugin-opt=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper] ==> ignore
    arg [-plugin-opt=-fresolution=/tmp/cc24JM9b.res] ==> ignore
    arg [-plugin-opt=-pass-through=-lgcc] ==> ignore
    arg [-plugin-opt=-pass-through=-lgcc_s] ==> ignore
    arg [-plugin-opt=-pass-through=-lc] ==> ignore
    arg [-plugin-opt=-pass-through=-lgcc] ==> ignore
    arg [-plugin-opt=-pass-through=-lgcc_s] ==> ignore
    arg [--sysroot=/] ==> ignore
    arg [--build-id] ==> ignore
    arg [--eh-frame-hdr] ==> ignore
    arg [-m] ==> ignore
    arg [elf_x86_64] ==> ignore
    arg [--hash-style=gnu] ==> ignore
    arg [-export-dynamic] ==> ignore
    arg [-dynamic-linker] ==> ignore
    arg [/lib64/ld-linux-x86-64.so.2] ==> ignore
    arg [-pie] ==> ignore
    arg [-o] ==> ignore
    arg [cmTC_98fbb] ==> ignore
    arg [/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/Scrt1.o] ==> ignore
    arg [/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/crti.o] ==> ignore
    arg [/usr/lib/gcc/x86_64-linux-gnu/6/crtbeginS.o] ==> ignore
    arg [-L/usr/lib/gcc/x86_64-linux-gnu/6] ==> dir [/usr/lib/gcc/x86_64-linux-gnu/6]
    arg [-L/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu] ==> dir [/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu]
    arg [-L/usr/lib/gcc/x86_64-linux-gnu/6/../../../../lib] ==> dir [/usr/lib/gcc/x86_64-linux-gnu/6/../../../../lib]
    arg [-L/lib/x86_64-linux-gnu] ==> dir [/lib/x86_64-linux-gnu]
    arg [-L/lib/../lib] ==> dir [/lib/../lib]
    arg [-L/usr/lib/x86_64-linux-gnu] ==> dir [/usr/lib/x86_64-linux-gnu]
    arg [-L/usr/lib/../lib] ==> dir [/usr/lib/../lib]
    arg [-L/usr/lib/gcc/x86_64-linux-gnu/6/../../..] ==> dir [/usr/lib/gcc/x86_64-linux-gnu/6/../../..]
    arg [CMakeFiles/cmTC_98fbb.dir/CMakeCCompilerABI.c.o] ==> ignore
    arg [-lgcc] ==> lib [gcc]
    arg [--as-needed] ==> ignore
    arg [-lgcc_s] ==> lib [gcc_s]
    arg [--no-as-needed] ==> ignore
    arg [-lc] ==> lib [c]
    arg [-lgcc] ==> lib [gcc]
    arg [--as-needed] ==> ignore
    arg [-lgcc_s] ==> lib [gcc_s]
    arg [--no-as-needed] ==> ignore
    arg [/usr/lib/gcc/x86_64-linux-gnu/6/crtendS.o] ==> ignore
    arg [/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/crtn.o] ==> ignore
  remove lib [gcc]
  remove lib [gcc_s]
  remove lib [gcc]
  remove lib [gcc_s]
  collapse library dir [/usr/lib/gcc/x86_64-linux-gnu/6] ==> [/usr/lib/gcc/x86_64-linux-gnu/6]
  collapse library dir [/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu] ==> [/usr/lib/x86_64-linux-gnu]
  collapse library dir [/usr/lib/gcc/x86_64-linux-gnu/6/../../../../lib] ==> [/usr/lib]
  collapse library dir [/lib/x86_64-linux-gnu] ==> [/lib/x86_64-linux-gnu]
  collapse library dir [/lib/../lib] ==> [/lib]
  collapse library dir [/usr/lib/x86_64-linux-gnu] ==> [/usr/lib/x86_64-linux-gnu]
  collapse library dir [/usr/lib/../lib] ==> [/usr/lib]
  collapse library dir [/usr/lib/gcc/x86_64-linux-gnu/6/../../..] ==> [/usr/lib]
  implicit libs: [c]
  implicit dirs: [/usr/lib/gcc/x86_64-linux-gnu/6;/usr/lib/x86_64-linux-gnu;/usr/lib;/lib/x86_64-linux-gnu;/lib]
  implicit fwks: []

Detecting C [-std=c11] compiler features compiled with the following output:
Change Dir: /home/flowforger/rtl-entropy/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_a9f07/fast"
/usr/bin/make -f CMakeFiles/cmTC_a9f07.dir/build.make CMakeFiles/cmTC_a9f07.dir/build
make[1]: Entering directory '/home/flowforger/rtl-entropy/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_a9f07.dir/feature_tests.c.o
/usr/bin/cc    -std=c11 -o CMakeFiles/cmTC_a9f07.dir/feature_tests.c.o   -c /home/flowforger/rtl-entropy/build/CMakeFiles/feature_tests.c
Linking C executable cmTC_a9f07
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_a9f07.dir/link.txt --verbose=1
/usr/bin/cc       CMakeFiles/cmTC_a9f07.dir/feature_tests.c.o  -o cmTC_a9f07 -rdynamic 
make[1]: Leaving directory '/home/flowforger/rtl-entropy/build/CMakeFiles/CMakeTmp'

    Feature record: C_FEATURE:1c_function_prototypes
    Feature record: C_FEATURE:1c_restrict
    Feature record: C_FEATURE:1c_static_assert
    Feature record: C_FEATURE:1c_variadic_macros

Detecting C [-std=c99] compiler features compiled with the following output:
Change Dir: /home/flowforger/rtl-entropy/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_75590/fast"
/usr/bin/make -f CMakeFiles/cmTC_75590.dir/build.make CMakeFiles/cmTC_75590.dir/build
make[1]: Entering directory '/home/flowforger/rtl-entropy/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_75590.dir/feature_tests.c.o
/usr/bin/cc    -std=c99 -o CMakeFiles/cmTC_75590.dir/feature_tests.c.o   -c /home/flowforger/rtl-entropy/build/CMakeFiles/feature_tests.c
Linking C executable cmTC_75590
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_75590.dir/link.txt --verbose=1
/usr/bin/cc       CMakeFiles/cmTC_75590.dir/feature_tests.c.o  -o cmTC_75590 -rdynamic 
make[1]: Leaving directory '/home/flowforger/rtl-entropy/build/CMakeFiles/CMakeTmp'

    Feature record: C_FEATURE:1c_function_prototypes
    Feature record: C_FEATURE:1c_restrict
    Feature record: C_FEATURE:0c_static_assert
    Feature record: C_FEATURE:1c_variadic_macros

Detecting C [-std=c90] compiler features compiled with the following output:
Change Dir: /home/flowforger/rtl-entropy/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_e829c/fast"
/usr/bin/make -f CMakeFiles/cmTC_e829c.dir/build.make CMakeFiles/cmTC_e829c.dir/build
make[1]: Entering directory '/home/flowforger/rtl-entropy/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_e829c.dir/feature_tests.c.o
/usr/bin/cc    -std=c90 -o CMakeFiles/cmTC_e829c.dir/feature_tests.c.o   -c /home/flowforger/rtl-entropy/build/CMakeFiles/feature_tests.c
Linking C executable cmTC_e829c
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_e829c.dir/link.txt --verbose=1
/usr/bin/cc       CMakeFiles/cmTC_e829c.dir/feature_tests.c.o  -o cmTC_e829c -rdynamic 
make[1]: Leaving directory '/home/flowforger/rtl-entropy/build/CMakeFiles/CMakeTmp'

    Feature record: C_FEATURE:1c_function_prototypes
    Feature record: C_FEATURE:0c_restrict
    Feature record: C_FEATURE:0c_static_assert
    Feature record: C_FEATURE:0c_variadic_macros

**Comment by K1773R** [comment]
RTFM: https://github.com/pwarren/rtl-entropy#dependencies

**Comment by pwarren** [comment]
Yeah, you'll need to install development libraries for: rtl-sdr, libcap and openssl
