### ISSUE TITLE
0 gain with Realtek Semiconductor Corp. RTL2838 DVB-T

### ISSUE THREAD

**Issue by js3263854** [pwarren/rtl-entropy#31]
Hello
I can't seem to get this device to work correctly, All the high entropy files are zero bytes.

I'm using a  Realtek Semiconductor Corp. RTL2838 DVB-T

foo@bar:~$ rtl_entropy -s 2.4M -f 101.5M -e | rngtest -c 500000 -p > high_entropy.bin
Options parsed, continuing.
Found 1 device(s):
  0:  Generic RTL2832U OEM
Using device 0: Generic RTL2832U OEM
Detached kernel driver
No supported tuner found
Enabled direct sampling mode, input 1
Setting Frequency to 101500000
Your device is capable of gains at...
 : 0.00
Setting gain to 0.00
Doing FIPS init
Reading samples in sync mode...

After running strace, I get this:
write(2, "Setting gain to 0.00", 20Setting gain to 0.00)    = 20
write(2, "\n", 1
)                       = 1
write(2, "Doing FIPS init", 15Doing FIPS init)         = 15
write(2, "\n", 1
)                       = 1
write(2, "Reading samples in sync mode...", 31Reading samples in sync mode...) = 31
write(2, "\n", 1
)                       = 1
ioctl(9, USBDEVFS_SUBMITURB, 0x1873670) = 0
poll([{fd=6, events=POLLIN}, {fd=8, events=POLLIN}, {fd=9, events=POLLOUT}], 3, 60000) = 1 ([{fd=9, revents=POLLOUT}])
ioctl(9, USBDEVFS_REAPURBNDELAY, 0xbfc17078) = 0
ioctl(9, USBDEVFS_REAPURBNDELAY, 0xbfc17078) = -1 EAGAIN (Resource temporarily unavailable)
ioctl(9, USBDEVFS_SUBMITURB, 0x1873670) = 0
poll([{fd=6, events=POLLIN}, {fd=8, events=POLLIN}, {fd=9, events=POLLOUT}], 3, 60000) = 1 ([{fd=9, revents=POLLOUT}])
ioctl(9, USBDEVFS_REAPURBNDELAY, 0xbfc17078) = 0
ioctl(9, USBDEVFS_REAPURBNDELAY, 0xbfc17078) = -1 EAGAIN (Resource temporarily unavailable)
ioctl(9, USBDEVFS_SUBMITURB, 0x1873670) = 0
poll([{fd=6, events=POLLIN}, {fd=8, events=POLLIN}, {fd=9, events=POLLOUT}], 3, 60000) = 1 ([{fd=9, revents=POLLOUT}])

Any ideas?

**Comment by K1773R** [comment]
Invalid for rtl-entropy because of:
```No supported tuner found```
Either the device is not supported or you use a too old librtlsdr. Opening a issue at their project will help.

**Comment by js3263854** [comment]
Thank you. I'll follow it up with librtlsdr, it was using the latest git cloned libs.
