### ISSUE TITLE
Feature request: rtl-sdr dump1090 RAW as input

### ISSUE THREAD

**Issue by lwqcz** [pwarren/rtl-entropy#37]
Hi there,

I've just discovered that my Pine A64 does not have any proper entropy source as it lacks hardware TRNG and `haveged` is not good enough also.

I'm running some modeS/ADS-B decoding there using `dump1090` and this utility produces RAW data output port numbered 30005.

Would it be possible to add a switch for rtl-entropy not to use hardware rtl-sdr but specified network IP:port ?
That would be great at many network-connected devices that can listen to that "random" data and use it as another source of entropy.

Please let me know, thanks 🍺

**Comment by yhaenggi** [comment]
If your interested to securely transmit entropy from a pool to multiple places, this might be of interest to you: https://www.vanheusden.com/entropybroker/
Also for randomness, you shouldn't sample a signal. Ideally you'd chose a frequency which is only static noise. If you still want to run this with ADSB and support is added, be sure to enable kaminsky debiasing.

**Comment by lwqcz** [comment]
@yhaenggi as much as possible debiasing I would rather run that for sure. Thnx for that link, I'll check it out. ADS-B + modeS + modeAC data from a radius of 250NM would be quite random - I would like to make a test of its randomness for sure.

**Comment by pwarren** [comment]
As @yhaenggi  says, this is a job for a different sort of tool. taking raw adsb data would produce some randomness, but would need different treatment to the way rtl_entropy does things.
